# Generated by Django 4.2.13 on 2024-09-09 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_manager", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="location",
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
