# Generated by Django 4.2.13 on 2024-07-16 18:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_manager", "0002_user_last_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserCharacteristics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("single", models.BooleanField()),
            ],
        ),
    ]
