# Generated by Django 4.2.13 on 2024-07-16 18:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_manager", "0003_usercharacteristics"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserCharacteristics",
        ),
    ]
