# Generated by Django 4.2.13 on 2024-07-17 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_manager", "0005_answers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answers",
            name="answer1",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="answers",
            name="answer2",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="answers",
            name="answer3",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
