# Generated by Django 4.2.13 on 2024-07-17 13:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_manager", "0006_alter_answers_answer1_alter_answers_answer2_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Answers",
        ),
    ]
