# Generated by Django 4.2.13 on 2024-07-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_manager", "0009_profile_answers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="answers",
        ),
        migrations.AddField(
            model_name="profile",
            name="answers",
            field=models.ManyToManyField(
                blank=True, null=True, to="user_manager.answers"
            ),
        ),
    ]
