# Generated by Django 4.2.13 on 2024-07-17 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user_manager", "0010_remove_profile_answers_profile_answers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="answers",
        ),
        migrations.AddField(
            model_name="profile",
            name="answers",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="user_manager.answers",
            ),
        ),
    ]
