# Generated by Django 4.2.13 on 2024-07-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_manager", "0011_remove_profile_answers_profile_answers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="answers",
        ),
        migrations.AddField(
            model_name="profile",
            name="characteristics",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Answers",
        ),
    ]
