# Generated by Django 4.2.13 on 2024-07-17 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "user_manager",
            "0012_remove_profile_answers_profile_characteristics_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Characteristic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ans1", models.CharField(blank=True, max_length=255)),
                (
                    "profile",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_manager.profile",
                    ),
                ),
            ],
        ),
    ]
