# Generated by Django 4.2.13 on 2024-07-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_manager", "0013_characteristic"),
    ]

    operations = [
        migrations.AddField(
            model_name="characteristic",
            name="ans2",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
