# Generated by Django 4.2.13 on 2024-07-17 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user_manager", "0014_characteristic_ans2"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="characteristic",
            name="ans1",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="characteristics",
        ),
        migrations.AddField(
            model_name="characteristic",
            name="user_type",
            field=models.CharField(
                choices=[
                    (None, ""),
                    ("Organiser", "Jestem organizatorem"),
                    ("Seeker", "Szukam wyjazdów"),
                    (
                        "seeker_and_organiser",
                        "Jestem organizatorem ale też szukam wyjazdów",
                    ),
                ],
                default=1,
                max_length=255,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="characteristic",
            name="ans2",
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name="characteristic",
            name="profile",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="characteristics",
                to="user_manager.profile",
            ),
            preserve_default=False,
        ),
    ]
