# Generated by Django 4.2.13 on 2024-07-17 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user_manager", "0015_remove_characteristic_ans1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="characteristic",
            name="profile",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="characteristics",
                to="user_manager.profile",
            ),
        ),
        migrations.AlterField(
            model_name="characteristic",
            name="user_type",
            field=models.CharField(
                choices=[
                    (None, ""),
                    ("Organiser", "Jestem organizatorem"),
                    ("Seeker", "Szukam wyjazdów"),
                    (
                        "seeker_and_organiser",
                        "Jestem organizatorem ale też szukam wyjazdów",
                    ),
                ],
                max_length=255,
                verbose_name="Określ się",
            ),
        ),
    ]
