# Generated by Django 4.2.13 on 2024-07-17 16:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_manager", "0016_alter_characteristic_profile_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="characteristic",
            old_name="ans2",
            new_name="is_single",
        ),
        migrations.AddField(
            model_name="characteristic",
            name="tourism_type",
            field=models.CharField(
                choices=[
                    (None, ""),
                    ("agritourism", "Agroturystyka"),
                    ("mountain", "Górska"),
                    ("urban", "Miejska"),
                    ("nature", "Przyrodnicza"),
                ],
                default=1,
                max_length=255,
                verbose_name="Jaki typ turystyki lubisz?",
            ),
            preserve_default=False,
        ),
    ]
