# Generated by Django 4.2.13 on 2024-07-18 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "user_manager",
            "0018_answer_question_userresponse_delete_characteristic_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="question",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="user_manager.question"
            ),
        ),
        migrations.AlterField(
            model_name="userresponse",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
