# Generated by Django 4.2.13 on 2024-07-18 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user_manager", "0019_alter_answer_question_alter_userresponse_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="user_manager.question"
            ),
        ),
    ]
