# Generated by Django 4.2.13 on 2024-07-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_manager", "0022_remove_answer_multiple_question_multiple_answer"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(default=1, upload_to=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="description",
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
