# Generated by Django 4.2.13 on 2024-07-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0025_remove_profile_avatar_profile_slug_user_has_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.URLField(default='def'),
            preserve_default=False,
        ),
    ]
