# Generated by Django 4.2.13 on 2024-07-20 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0026_profile_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='multiple_answer',
            new_name='is_multiple_answer',
        ),
        migrations.AddField(
            model_name='question',
            name='is_profile',
            field=models.BooleanField(default=False),
        ),
    ]
