# Generated by Django 4.2.13 on 2024-07-28 11:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0031_sharedpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpost',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventpost',
            name='when',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='eventpost',
            name='where',
            field=models.CharField(default='kajo', max_length=255),
            preserve_default=False,
        ),
    ]
