# Generated by Django 4.2.13 on 2024-07-29 11:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "user_manager",
            "0003_alter_profile_location",
        ),
    ]

    operations = []
