# Generated by Django 4.2.13 on 2024-07-29 11:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "user_manager",
            "0033_user_created_at",
        ),
        ("user_manager", "0033_user_created_at"),
    ]

    operations = []
