# Generated by Django 4.2.13 on 2024-08-23 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user_manager", "0034_merge_20240729_1127"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("photo", "photo"),
                            ("video", "video"),
                            ("file", "file"),
                        ],
                        max_length=6,
                    ),
                ),
                ("attachment_url", models.URLField()),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="user_manager.post",
                    ),
                ),
            ],
        ),
    ]
