# Generated by Django 4.2.13 on 2024-08-23 05:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_manager", "0035_postattachment"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PostAttachment",
        ),
    ]
