# Generated by Django 4.2.13 on 2024-08-23 06:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_manager", "0038_eventpost_date_end_eventpost_date_start"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventpost",
            name="date_start",
        ),
    ]
