# Generated by Django 4.2.13 on 2024-08-23 21:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_manager", "0040_eventpost_number_of_people"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventpost",
            name="date_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
