# Generated by Django 4.2.13 on 2024-08-23 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user_manager", "0041_alter_eventpost_date_end"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventPostType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(default="Nieznany", max_length=255)),
                (
                    "event_post",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="user_manager.eventpost",
                    ),
                ),
            ],
        ),
    ]
