# Generated by Django 4.2.13 on 2024-08-23 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user_manager", "0042_eventposttype"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventposttype",
            name="event_post",
        ),
        migrations.AddField(
            model_name="eventpost",
            name="event_post",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="user_manager.eventposttype",
            ),
        ),
    ]
