# Generated by Django 4.2.13 on 2024-08-25 09:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_manager", "0043_remove_eventposttype_event_post_eventpost_event_post"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventpost",
            name="event_post",
        ),
    ]
