# Generated by Django 4.2.13 on 2024-09-06 06:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_manager", "0036_delete_postattachment"),
        ("user_manager", "0044_remove_eventpost_event_post"),
    ]

    operations = []
