# Generated by Django 4.2.13 on 2024-09-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0045_question_requires_text_input'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='text_answer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
