# Generated by Django 4.2.13 on 2024-09-05 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0046_userresponse_text_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresponse',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_manager.answer'),
        ),
    ]
